import About from "@/components/About";
import Main from "@/components/Main";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Contact from "@/components/Contact";
import Head from "next/head";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Clint | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
